## Assignment: Notebook for Week 5 of Databases and SQL

In [6]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [7]:
%sql ibm_db_sa://hct37227:Hghmo6KVcvybjWvx@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB?security=SSL

'Connected: hct37227@BLUDB'

In [8]:
%sql select * from syscat.columns where tabname = 'CHICAGO_CRIME_DATA'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('HCT37227', 'CHICAGO_CRIME_DATA', 'ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'CASE_NUMBER', 1, 'SYSIBM  ', 'VARCHAR', 8, 0, 'OCTETS', 8, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'DATE', 2, 'SYSIBM  ', 'DATE', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'BLOCK', 3, 'SYSIBM  ', 'VARCHAR', 35, 0, 'OCTETS', 35, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'IUCR', 4, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'PRIMARY_TYPE', 5, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'DESCRIPTION', 6, 'SYSIBM  ', 'VARCHAR', 46, 0, 'OCTETS', 46, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'LOCATION_DESCRIPTION', 7, 'SYSIBM  ', 'VARCHAR', 33, 0, 'OCTETS', 33, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'ARREST', 8, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'DOMESTIC', 9, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'BEAT', 10, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'DISTRICT', 11, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'WARD', 12, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'COMMUNITY_AREA_NUMBER', 13, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'FBICODE', 14, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'X_COORDINATE', 15, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'Y_COORDINATE', 16, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'YEAR', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'LATITUDE', 18, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'LONGITUDE', 19, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CRIME_DATA', 'LOCATION', 20, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [10]:
%sql select count(ID) as total_crimes from CHICAGO_CRIME_DATA

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(533,)]

In [14]:
%%sql 
select community_area_name, per_capita_income
from chicago_census_data
where per_capita_income<11000

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

In [20]:
%sql select * from syscat.columns where tabname = 'CHICAGO_CENSUS_DATA'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('HCT37227', 'CHICAGO_CENSUS_DATA', 'COMMUNITY_AREA_NUMBER', 0, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'COMMUNITY_AREA_NAME', 1, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'PERCENT_OF_HOUSING_CROWDED', 2, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'PERCENT_HOUSEHOLDS_BELOW_POVERTY', 3, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'PERCENT_AGED_16__UNEMPLOYED', 4, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA', 5, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'PERCENT_AGED_UNDER_18_OR_OVER_64', 6, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'PER_CAPITA_INCOME', 7, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_CENSUS_DATA', 'HARDSHIP_INDEX', 8, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [30]:
%sql select * from syscat.columns where tabname = 'CHICAGO_PUBLIC_SCHOOLS'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'SCHOOL_ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'NAME_OF_SCHOOL', 1, 'SYSIBM  ', 'VARCHAR', 64, 0, 'OCTETS', 64, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'Elementary, Middle, or High School', 2, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'STREET_ADDRESS', 3, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'CITY', 4, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'STATE', 5, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'ZIP_CODE', 6, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PHONE_NUMBER', 7, 'SYSIBM  ', 'VARCHAR', 14, 0, 'OCTETS', 14, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'LINK', 8, 'SYSIBM  ', 'VARCHAR', 78, 0, 'OCTETS', 78, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'NETWORK_MANAGER', 9, 'SYSIBM  ', 'VARCHAR', 40, 0, 'OCTETS', 40, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'COLLABORATIVE_NAME', 10, 'SYSIBM  ', 'VARCHAR', 34, 0, 'OCTETS', 34, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'ADEQUATE_YEARLY_PROGRESS_MADE_', 11, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'TRACK_SCHEDULE', 12, 'SYSIBM  ', 'VARCHAR', 12, 0, 'OCTETS', 12, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'CPS_PERFORMANCE_POLICY_STATUS', 13, 'SYSIBM  ', 'VARCHAR', 16, 0, 'OCTETS', 16, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'CPS_PERFORMANCE_POLICY_LEVEL', 14, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'HEALTHY_SCHOOL_CERTIFIED', 15, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'SAFETY_ICON', 16, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'SAFETY_SCORE', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'FAMILY_INVOLVEMENT_ICON', 18, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'FAMILY_INVOLVEMENT_SCORE', 19, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'ENVIRONMENT_ICON', 20, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'ENVIRONMENT_SCORE', 21, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'INSTRUCTION_ICON', 22, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'INSTRUCTION_SCORE', 23, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'LEADERS_ICON', 24, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'LEADERS_SCORE', 25, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'TEACHERS_ICON', 26, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'TEACHERS_SCORE', 27, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PARENT_ENGAGEMENT_ICON', 28, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PARENT_ENGAGEMENT_SCORE', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PARENT_ENVIRONMENT_ICON', 30, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PARENT_ENVIRONMENT_SCORE', 31, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'AVERAGE_STUDENT_ATTENDANCE', 32, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'RATE_OF_MISCONDUCTS__PER_100_STUDENTS_', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'AVERAGE_TEACHER_ATTENDANCE', 34, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'INDIVIDUALIZED_EDUCATION_PROGRAM_COMPLIANCE_RATE', 35, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PK_2_LITERACY__', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'PK_2_MATH__', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR3_5_GRADE_LEVEL_MATH__', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR3_5_GRADE_LEVEL_READ__', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR3_5_KEEP_PACE_READ__', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR3_5_KEEP_PACE_MATH__', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR6_8_GRADE_LEVEL_MATH__', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR6_8_GRADE_LEVEL_READ__', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR6_8_KEEP_PACE_MATH_', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('HCT37227', 'CHICAGO_PUBLIC_SCHOOLS', 'GR6_8_KEEP_PACE_READ__', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [17]:
%%sql

select case_number, description 
from chicago_crime_data 
where description like '%MINOR%'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('HL266884', 'SELL/GIVE/DEL LIQUOR TO MINOR'),
 ('HK238408', 'ILLEGAL CONSUMPTION BY MINOR')]

In [18]:
%%sql
select case_number, description 
from chicago_crime_data 
where description like '%CHILD%'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('HN567387', 'AGG SEX ASSLT OF CHILD FAM MBR'),
 ('HR391350', 'SEX ASSLT OF CHILD BY FAM MBR'),
 ('HN144152', 'CHILD ABDUCTION/STRANGER')]

In [ ]:
%%sql
select distinct primary_type, description 
from chicago_crime_data 
order by 1;

In [9]:
%%sql
select case_number, primary_type, description 
from chicago_crime_data 
where primary_type = 'KIDNAPPING' AND description like '%CHILD%'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('HN144152', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER')]

In [29]:
%%sql
select distinct primary_type, description 
from chicago_crime_data 
where location_description like '%SCHOOL%'

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('PUBLIC PEACE VI', 'BOMB THREAT'),
 ('NARCOTICS', 'MANU/DEL:CANNABIS 10GM OR LESS'),
 ('NARCOTICS', 'POSS: HEROIN(WHITE)'),
 ('ASSAULT', 'PRO EMP HANDS NO/MIN INJURY'),
 ('BATTERY', 'PRO EMP HANDS NO/MIN INJURY'),
 ('BATTERY', 'SIMPLE'),
 ('CRIMINAL TRESPA', 'TO LAND'),
 ('CRIMINAL DAMAGE', 'TO VEHICLE')]

In [32]:
%sql select AVG(SAFETY_SCORE) as ave_safety_score from chicago_public_schools

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(49,)]

In [33]:
%%sql 
select COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY
from chicago_census_data
order by PERCENT_HOUSEHOLDS_BELOW_POVERTY desc limit 5

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[('Riverdale', Decimal('56.5')),
 ('Fuller Park', Decimal('51.2')),
 ('Englewood', Decimal('46.6')),
 ('North Lawndale', Decimal('43.1')),
 ('East Garfield Park', Decimal('42.4'))]

In [42]:
%%sql 
select count(*) as number_of_crimes, COMMUNITY_AREA_NUMBER
from chicago_crime_data
where COMMUNITY_AREA_NUMBER is not null
group by COMMUNITY_AREA_NUMBER
order by number_of_crimes desc limit 1

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(43, 25)]

In [43]:
%%sql 
select hardship_index, community_area_name
from chicago_census_data
where hardship_index = (select max(hardship_index) as max_hardship_index from chicago_census_data)

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(98, 'Riverdale')]

In [71]:
%%sql 
select COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME from chicago_census_data 
where COMMUNITY_AREA_NUMBER in (select community_area_number 
                                from chicago_crime_data 
                                order by community_area_number desc nulls last limit 1)

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(77, 'Edgewater')]

In [97]:
%%sql 
select community_area_number, count(id) as crime_count from chicago_crime_data
group by community_area_number
order by crime_count desc limit 1

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(25, 43)]

In [111]:
%%sql 
select ce.community_area_number, count(case_number) as crime_count, community_area_name
from chicago_crime_data cr, chicago_census_data ce
where ce.community_area_number = cr.community_area_number
group by ce.community_area_number, community_area_name
order by crime_count desc limit 1

 * ibm_db_sa://hct37227:***@2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30756/BLUDB
Done.

[(25, 43, 'Austin')]